# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main: 
  - name: Apple
    url: apple/
    weight: 2
  - name: Linux
    url: linux/
    weight: 3
  - name: Stuff
    url: stuff/
    weight: 4